server.port=8080

moxo.api.base=https://kotak.moxtra.com
moxo.org.id=POeZu2KT3ZpL2LRdFXut9gL
moxo.client.id=NjEwNWFiOGY
moxo.client.secret=YmU5YmRlNjY
moxo.admin.email=aditya.nayak@moxo.com
moxo.webhook.url=https://kotak.moxtra.com/integration/application/webhook/workspace/create?template_id=BKmrEq596z58Vg0JFMPtecH

# Comma-separated list of RM emails and names (email:name pairs)
moxo.rm.list=internal_rm_1@yopmail.com:Internal RM 1,internal_rm_2@yopmail.com:Internal RM 2,internal_rm_3@yopmail.com:Internal RM 3
